Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonalBlog.Data;

namespace PersonalBlog.Controllers
{
    public class AboutController : Controller
    {
        private readonly PersonalBlogContext _context;

        public AboutController(PersonalBlogContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var about = _context.Abouts.FirstOrDefault();
            ViewBag.Skills = _context.Skills.ToList();
            ViewBag.Educations = _context.Educations.ToList();
            ViewBag.Experiences = _context.Experiences.ToList();
            return View(about);
        }
    }
}

Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalBlog.Data;
using PersonalBlog.Services;
using Microsoft.Extensions.Configuration;

namespace PersonalBlog.Controllers
{
    public class AdminController : Controller
    {
        private readonly PersonalBlogContext _context;
        private readonly AuthService _authService;
        private readonly IConfiguration _configuration;

        public AdminController(PersonalBlogContext context, AuthService authService, IConfiguration configuration)
        {
            _context = context;
            _authService = authService;
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");

            var about = _context.Abouts.FirstOrDefault();
            return View(about);
        }
        public IActionResult About()
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");

            var about = _context.Abouts.FirstOrDefault();
            ViewBag.Skills = _context.Skills.ToList();
            ViewBag.Educations = _context.Educations.ToList();
            ViewBag.Experiences = _context.Experiences.ToList();
            return View(about);
        }
        [HttpPost]
        public IActionResult UpdateAbout(About about)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");

            var existingAbout = _context.Abouts.FirstOrDefault();
            if (existingAbout != null)
            {
                existingAbout.FullName = about.FullName;
                existingAbout.Job = about.Job;
                existingAbout.Bio = about.Bio;
                existingAbout.Birthday = about.Birthday;
                existingAbout.Age = about.Age;
                existingAbout.Degree = about.Degree;
                existingAbout.Email = about.Email;
                existingAbout.Freelance = about.Freelance;
                existingAbout.City = about.City;
                existingAbout.Phone = about.Phone;
                existingAbout.Github = about.Github;
                existingAbout.Facebook = about.Facebook;
                existingAbout.Instagram = about.Instagram;

                _context.SaveChanges();
            }

            return RedirectToAction("About");
        }

        [HttpPost]
        public IActionResult CreateSkill(Skill skill)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            _context.Skills.Add(skill);
            _context.SaveChanges();
            return RedirectToAction("About");
        }
        [HttpPost]
        public IActionResult UpdateSkill(Skill skill)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            var existingSkill = _context.Skills.Find(skill.Id);
            if (existingSkill != null)
            {
                existingSkill.SkillName = skill.SkillName;
                existingSkill.Proficiency = skill.Proficiency;
                _context.SaveChanges();
            }
            return RedirectToAction("About");
        }

        public IActionResult DeleteSkill(int id)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            var skill = _context.Skills.Find(id);
            if (skill != null)
            {
                _context.Skills.Remove(skill);
                _context.SaveChanges();
            }
            return RedirectToAction("About");
        }

        [HttpPost]
        public IActionResult CreateEducation(Education education)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            _context.Educations.Add(education);
            _context.SaveChanges();
            return RedirectToAction("About");
        }
        [HttpPost]
        public IActionResult UpdateEducation(Education education)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            var existingEducation = _context.Educations.Find(education.Id);
            if (existingEducation != null)
            {
                existingEducation.Title = education.Title;
                existingEducation.Description = education.Description;
                existingEducation.StartYear = education.StartYear;
                existingEducation.EndYear = education.EndYear;
                _context.SaveChanges();
            }
            return RedirectToAction("About");
        }
        public IActionResult DeleteEducation(int id)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            var education = _context.Educations.Find(id);
            if (education != null)
            {
                _context.Educations.Remove(education);
                _context.SaveChanges();
            }
            return RedirectToAction("About");
        }
        [HttpPost]
        public IActionResult CreateExperience(Experience experience)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            _context.Experiences.Add(experience);
            _context.SaveChanges();
            return RedirectToAction("About");
        }
        [HttpPost]
        public IActionResult UpdateExperience(Experience experience)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            var existingExperience = _context.Experiences.Find(experience.Id);
            if (existingExperience != null)
            {
                existingExperience.Title = experience.Title;
                existingExperience.StartYear = experience.StartYear;
                existingExperience.EndYear = experience.EndYear;
                existingExperience.Description = experience.Description;
                _context.SaveChanges();
            }
            return RedirectToAction("About");
        }
        public IActionResult DeleteExperience(int id)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            var experience = _context.Experiences.Find(id);
            if (experience != null)
            {
                _context.Experiences.Remove(experience);
                _context.SaveChanges();
            }
            return RedirectToAction("About");
        }
        public IActionResult Service()
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            var services = _context.Services.ToList();
            return View(services);
        }
        [HttpPost]
        public IActionResult CreateService(Service service)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            _context.Services.Add(service);
            _context.SaveChanges();
            return RedirectToAction("Service");
        }
        [HttpPost]
        public IActionResult UpdateService(Service service)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            var existingService = _context.Services.Find(service.Id);
            if (existingService != null)
            {
                existingService.ServiceName = service.ServiceName;
                existingService.Description = service.Description;
                existingService.Icon = service.Icon;
                _context.SaveChanges();
            }
            return RedirectToAction("Service");
        }
        public IActionResult DeleteService(int id)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            var service = _context.Services.Find(id);
            if (service != null)
            {
                _context.Services.Remove(service);
                _context.SaveChanges();
            }
            return RedirectToAction("Service");
        }
        public IActionResult Portfolio()
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");

            var portfolios = _context.Portfolios.ToList();
            return View(portfolios);
        }
        [HttpPost]
        public IActionResult CreatePortfolio(Portfolio portfolio)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            _context.Portfolios.Add(portfolio);
            _context.SaveChanges();
            return RedirectToAction("Portfolio");
        }
        [HttpPost]
        public IActionResult UpdatePortfolio(Portfolio portfolio)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            var existingPortfolio = _context.Portfolios.Find(portfolio.Id);
            if (existingPortfolio != null)
            {
                existingPortfolio.Title = portfolio.Title;
                existingPortfolio.Description = portfolio.Description;
                existingPortfolio.Image = portfolio.Image;
                existingPortfolio.Link = portfolio.Link;
                existingPortfolio.Category = portfolio.Category;
                _context.SaveChanges();
            }
            return RedirectToAction("Portfolio");
        }
        public IActionResult DeletePortfolio(int id)
        {
            if (!_authService.IsAdminLoggedIn())
                return RedirectToAction("Login");
            var portfolio = _context.Portfolios.Find(id);
            if (portfolio != null)
            {
                _context.Portfolios.Remove(portfolio);
                _context.SaveChanges();
            }

Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalBlog.Data;

namespace PersonalBlog.Controllers
{
    public class BlogController : Controller
    {
        private readonly PersonalBlogContext _context;

        public BlogController(PersonalBlogContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.Blogs = _context.Blogs.ToList();    
            return View();
        }
        public IActionResult Details(int id)
        {
            var blog = _context.Blogs.FirstOrDefault(b => b.Id == id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }
    }
}

Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using PersonalBlog.Data;

namespace PersonalBlog.Controllers
{
    public class ServicesController : Controller
    {
        private readonly PersonalBlogContext _context;

        public ServicesController(PersonalBlogContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.Services = _context.Services.ToList();
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>@ViewBag.Title - Personal Portfolio</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Template css Files -->
    <link rel="stylesheet" href="~/css/style.css" type="text/css">

    <!-- Live Style Switcher - Demo Only -->
    <link rel="stylesheet" class="alternate-style" title="pink" href="~/css/skins/pink.css" type="text/css">
    <link rel="stylesheet" class="alternate-style" title="blue" href="~/css/skins/blue.css" type="text/css" disabled>
    <link rel="stylesheet" class="alternate-style" title="green" href="~/css/skins/green.css" type="text/css" disabled>
    <link rel="stylesheet" class="alternate-style" title="orange" href="~/css/skins/orange.css" type="text/css" disabled>
    <link rel="stylesheet" class="alternate-style" title="yellow" href="~/css/skins/yellow.css" type="text/css" disabled>
    <link rel="stylesheet" href="~/css/styleSwitcher.css" type="text/css">
</head>
<body>
    <!-- Preloader -->
    <div class="preloader">
        <div class="loader"></div>
    </div>
    <!-- Preloader End -->
    <!-- Main Container -->
    <div class="main-container">
        <!-- Aside -->
        <div class="aside">
            <!-- Nav Toggler Btn -->
            <div class="nav-toggler">
                <span></span>
            </div>
            <div class="aside-inner">
                <!-- Logo -->
                <div class="logo">
                    <a href="@Url.Action("Index", "Home")">VanThuan</a>
                </div>
                <!-- Nav -->
                <ul class="nav">
                    <li>
                        <a href="@Url.Action("Index", "Home")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "Home" ? "active" : "")">
                            <i class="fa fa-home"></i> Home
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "About")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "About" ? "active" : "")">
                            <i class="fa fa-user"></i> About
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Services")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "Services" ? "active" : "")">
                            <i class="fa fa-list"></i> Services
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Portfolio")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "Portfolio" ? "active" : "")">
                            <i class="fa fa-briefcase"></i> Portfolio
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Blog")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "Blog" ? "active" : "")">
                            <i class="fa fa-envelope"></i> Blog
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Contact")"
                           class="@(ViewContext.RouteData.Values["controller"].ToString() == "Contact" ? "active" : "")">
                            <i class="fa fa-comments"></i> Contact
                        </a>
                    </li>
                </ul>

                <!-- Copyright -->
                <div class="copyright-text">
                    &copy; 2020 The WebShala Template
                </div>
            </div>
        </div>
        <!-- Aside End -->
        <!-- Main Content -->
        <div class="main-content">
            @RenderBody()
        </div>
        <!-- Main Content End -->
    </div>
    <!-- Main Container End -->
    <!-- Lightbox -->
    <div class="lightbox">
        <div class="lightbox-content">
            <div class="lightbox-close">&times;</div>
            <img src="" alt="" onclick="nextItem()" class="lightbox-img">
            <div class="lightbox-caption">
                <div class="caption-text"></div>
                <div class="caption-counter"></div>
            </div>
        </div>
        <div class="lightbox-controls">
            <div class="prev-item" onclick="prevItem()"><i class="fa fa-angle-left"></i></div>
            <div class="next-item" onclick="nextItem()"><i class="fa fa-angle-right"></i></div>
        </div>
    </div>
    <!-- Lightbox End -->
    <!-- Live Style Switcher - Demo Only -->
    <div class="style-switcher">
        <div class="toggle-style-switcher">
            <i class="fa fa-cog fa-spin"></i>
        </div>
        <h5>Style Switcher</h5>
        <ul>
            <li><a href="javascript:void(0);" title="pink" style="background-color: #ec1839;" onclick="setActiveStyle('pink')"></a></li>
            <li><a href="javascript:void(0);" title="blue" style="background-color: #2196f3;" onclick="setActiveStyle('blue')"></a></li>
            <li><a href="javascript:void(0);" title="orange" style="background-color: #fa5b0f;" onclick="setActiveStyle('orange')"></a></li>
            <li><a href="javascript:void(0);" title="yellow" style="background-color: #ffb400;" onclick="setActiveStyle('yellow')"></a></li>
            <li><a href="javascript:void(0);" title="green" style="background-color: #72b626;" onclick="setActiveStyle('green')"></a></li>
        </ul>
        <h5>Body Skin</h5>
        <label>
            <input type="radio" class="body-skin" name="body-skin" value="light" checked="true"> Light
        </label>
        <label>
            <input type="radio" class="body-skin" name="body-skin" value="dark"> Dark
        </label>
    </div>
    <!-- Live Style Switcher - Demo Only End -->
    <!-- Plugins -->
    <script src="~/js/ityped.min.js"></script>
    <!-- Template js -->
    <script src="~/js/script.js"></script>
    <!-- Live Style Js - Demo Only -->
    <script src="~/js/styleSwitcher.js"></script>
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>@ViewBag.Title - Personal Portfolio</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Template css Files -->
    <link rel="stylesheet" href="~/css/style.css" type="text/css">

    <!-- Live Style Switcher - Demo Only -->
    <link rel="stylesheet" class="alternate-style" title="pink" href="~/css/skins/pink.css" type="text/css">
    <link rel="stylesheet" class="alternate-style" title="blue" href="~/css/skins/blue.css" type="text/css" disabled>
    <link rel="stylesheet" class="alternate-style" title="green" href="~/css/skins/green.css" type="text/css" disabled>
    <link rel="stylesheet" class="alternate-style" title="orange" href="~/css/skins/orange.css" type="text/css" disabled>
    <link rel="stylesheet" class="alternate-style" title="yellow" href="~/css/skins/yellow.css" type="text/css" disabled>
    <link rel="stylesheet" href="~/css/styleSwitcher.css" type="text/css">
</head>
<body>
    <!-- Preloader -->
    <div class="preloader">
        <div class="loader"></div>
    </div>
    <!-- Preloader End -->
    <!-- Main Container -->
    <div class="main-container">
        <!-- Aside -->
        <div class="aside">
            <!-- Nav Toggler Btn -->
            <div class="nav-toggler">
                <span></span>
            </div>
            <div class="aside-inner">
                <!-- Logo -->
                <div class="logo">
                    <a href="@Url.Action("Index", "Admin")">VanThuan</a>
                </div>
                <!-- Nav -->
                <ul class="nav">
                    <ul class="nav">
                        <li>
                            <a href="@Url.Action("Index", "Admin")"
                               class="@(ViewContext.RouteData.Values["action"].ToString() == "Index" ? "active" : "")">
                                <i class="fa fa-home"></i> Home
                            </a>
                        </li>

                        <li>
                            <a href="@Url.Action("About", "Admin")"
                               class="@(ViewContext.RouteData.Values["action"].ToString() == "About" ? "active" : "")">
                                <i class="fa fa-user"></i> About
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Service", "Admin")"
                               class="@(ViewContext.RouteData.Values["action"].ToString() == "Service" ? "active" : "")">
                                <i class="fa fa-list"></i> Service
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Portfolio", "Admin")"
                               class="@(ViewContext.RouteData.Values["action"].ToString() == "Portfolio" ? "active" : "")">
                                <i class="fa fa-briefcase"></i> Portfolio
                            </a>
                        </li>

                        <li>
                            <a href="@Url.Action("Blog", "Admin")"
                               class="@(ViewContext.RouteData.Values["action"].ToString() == "Blog" ? "active" : "")">
                                <i class="fa fa-pencil"></i> Blog
                            </a>
                        </li>

                    </ul>

                </ul>

                <!-- Copyright -->
                <div class="copyright-text">
                    &copy; 2020 The WebShala Template
                </div>
            </div>
        </div>
        <!-- Aside End -->
        <!-- Main Content -->
        <div class="main-content">
            @RenderBody()
        </div>
        <!-- Main Content End -->
    </div>
    <!-- Main Container End -->
    <!-- Lightbox -->
    <div class="lightbox">
        <div class="lightbox-content">
            <div class="lightbox-close">&times;</div>
            <img src="" alt="" onclick="nextItem()" class="lightbox-img">
            <div class="lightbox-caption">
                <div class="caption-text"></div>
                <div class="caption-counter"></div>
            </div>
        </div>
        <div class="lightbox-controls">
            <div class="prev-item" onclick="prevItem()"><i class="fa fa-angle-left"></i></div>
            <div class="next-item" onclick="nextItem()"><i class="fa fa-angle-right"></i></div>
        </div>
    </div>
    <!-- Lightbox End -->
    <!-- Live Style Switcher - Demo Only -->
    <div class="style-switcher">
        <div class="toggle-style-switcher">
            <i class="fa fa-cog fa-spin"></i>
        </div>
        <h5>Style Switcher</h5>
        <ul>
            <li><a href="javascript:void(0);" title="pink" style="background-color: #ec1839;" onclick="setActiveStyle('pink')"></a></li>
            <li><a href="javascript:void(0);" title="blue" style="background-color: #2196f3;" onclick="setActiveStyle('blue')"></a></li>
            <li><a href="javascript:void(0);" title="orange" style="background-color: #fa5b0f;" onclick="setActiveStyle('orange')"></a></li>
            <li><a href="javascript:void(0);" title="yellow" style="background-color: #ffb400;" onclick="setActiveStyle('yellow')"></a></li>
            <li><a href="javascript:void(0);" title="green" style="background-color: #72b626;" onclick="setActiveStyle('green')"></a></li>
        </ul>
        <h5>Body Skin</h5>
        <label>
            <input type="radio" class="body-skin" name="body-skin" value="light" checked="true"> Light
        </label>
        <label>
            <input type="radio" class="body-skin" name="body-skin" value="dark"> Dark
        </label>
    </div>
    <!-- Live Style Switcher - Demo Only End -->
    <!-- Plugins -->
    <script src="~/js/ityped.min.js"></script>
    <!-- Template js -->
    <script src="~/js/script.js"></script>
    <!-- Live Style Js - Demo Only -->
    <script src="~/js/styleSwitcher.js"></script>
</body>
</html>